#%RAML 0.8
title: Fotodump
baseUri: /fotodump
securitySchemes:
  - oauth:
      type:
        Basic Authentication

/fotodump:
  displayName: Foto dump
  post:
    body:
      application/octet-stream:
    responses:
      303:
        headers:
          Location:
            type: string
      400:
  /{id}:
    get:
      body:
        application/octet-stream:
      responses:
        200:
        404:
    /tag:
      post:
        body:
          application/json:
        responses:
          200:
          400:
          404:
      get:
        body:
          application/json:
        responses:
          200:
          404:
